# Generated by Django 5.0.6 on 2024-07-08 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.DeleteModel(
            name='Stylist',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('B', 'Blowout'), ('WCS', 'Womens Cut & Style'), ('WMC', 'Womens Master Cut & Style'), ('MCW', 'Mens Wash & Scissor Cut'), ('LMC', 'Lengthy Master Color'), ('BMC', 'Buzz Master Color'), ('F', 'Fix Your Face'), ('FF', 'Face First')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='stylist',
            field=models.CharField(choices=[('A', 'Annabelle'), ('C', 'Corey'), ('D', 'Devlin'), ('G', 'Giang'), ('S', 'Scott')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
